Vagrant.configure("2") do |config|

  # centos/stream10: manage
  # https://portal.cloud.hashicorp.com/vagrant/discover/centos/stream10
  config.vm.define "manage" do |manage|

    manage.vm.box = "centos/stream10"
    manage.vm.box_version = "20260105.0"
    manage.vm.box_download_insecure = true

    # Disk (Rancher UI için 20GB önerilir)
    manage.vm.disk :disk, size: "20GB", primary: true

    # Network
    manage.vm.network "public_network",
                      bridge: "Realtek PCIe GbE Family Controller"

    # Provider
    manage.vm.provider "virtualbox" do |vb|
      vb.memory = 3048   # Rancher UI için 4048 önerilir
      vb.cpus  = 3
      vb.customize ["modifyvm", :id, "--audio", "none"]
    end

    # Provision
    manage.vm.provision "shell",
                        path: "setup-manage.sh",
                        privileged: true
  end

end
